
services:
  # Redis service for communication
  # redis:
  #   image: redis:7-alpine
  #   container_name: turtlebot_redis
  #   ports:
  #     - "6379:6379"
  #   networks:
  #     - turtlebot_network

  # TurtleBot Dash Simulator
  turtlebot_dash:
    build: .
    container_name: turtlebot_dash_simulator
    ports:
      - "8051:8051"
    environment:
      - DASH_HOST=0.0.0.0
      - DASH_PORT=8051
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    # depends_on:
    #   - redis
    networks:
      - turtlebot_network

networks:
  turtlebot_network:
    name: turtlebot_network
    driver: bridge
